# Generated by Django 4.1.7 on 2023-05-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_students_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='login_info',
        ),
    ]
