# Generated by Django 4.2.2 on 2023-07-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_logininfo_delete_login_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logininfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
