# Generated by Django 4.2.2 on 2023-07-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_logininfo_email_alter_logininfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
